### ISSUE TITLE
ESRI Map Tiles Throwing 500 Errors

### ISSUE THREAD

**Issue by jimjeffers** [mbari-org/dash5#216]
**Describe the bug**
It looks like the legacy API we've been using to access ESRI's ocean map layer is returning 500 errors preventing tiles from reliably loading into leaflet.

**To Reproduce**
1. Visit: https://mbari.vercel.app
2. Add at least one or two vehicles
3. View the resulting map on the main screen or view a deployment

**Expected behavior**
The map should not have any missing gray areas in place of failed tiles.

**Screenshots**
<img width="1728" alt="CleanShot 2023-01-14 at 09 50 52@2x" src="https://user-images.githubusercontent.com/9150/212487935-c5bcbce9-e8e0-4441-aab5-5bc87c083533.png">

![CleanShot 2023-01-14 at 09 51 31@2x](https://user-images.githubusercontent.com/9150/212487934-be0c1006-b354-470c-8813-3c824c065945.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Safari
 - Version 15.4

**Comment by jimjeffers** [comment]
@ksalamy if you want to give your API key a try - you may need to add this library to the project in addition to `esri-leaflet`:
https://github.com/slutske22/react-esri-leaflet

**Comment by ksalamy** [comment]
I believe this issue is now fixed. I used my own ArcGIS ESRI_API_KEY with the new basemap layer service information. The UI now loads to the original ESRI Oceans/Labels map.

**Comment by beroe** [comment]
This might be expected behavior, but If I zoom in 10 clicks from full wide, I get 404 errors on the tiles. 

Is there a maxzoom flag that is set?

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/871533/228443515-cef9386e-9216-4e7e-9aea-3f1763ab2668.png">
