### ISSUE TITLE
Enable Mission / Command UI in Inactive Deployments

### ISSUE THREAD

**Issue by jimjeffers** [mbari-org/dash5#242]
The UI blocks users from running missions or commands under the schedule tab. The original intent was that this shouldn't be possible while viewing something in the past. However, testers have raised the need to do this in order to prep for new deployments.

I believe you should be able to activate the UI on inactive schedules by adjusting the logic that adjusts for any `activeDeployment` state. You'll want to ensure you still inject at least 1 static header cell:

https://github.com/mbari-org/dash5/blob/0b527bff294ea6e20a4070bf4612198680a57503/apps/lrauv-dash2/components/ScheduleSection.tsx#L73

```ts
const scheduledTypes = ['pending', 'running']
  const staticHeaderCellOffset = activeDeployment ? 2 : 0
  const indexOfPastSchedule =
    (missions?.findIndex((v) => !scheduledTypes.includes(v.status)) ?? 0) +
    staticHeaderCellOffset
  const hasPastSchedule = indexOfPastSchedule > -1
  const staticFilterCellOffset = hasPastSchedule ? 1 : 0
```

And update the logic we look here.. removing the condition to return the cell at index 0 should do the trick. You may want to hide the or toggle the "scheduled until" label with the condition instead. There could be a few downstream bugs you may have to deal with in the `cellAtIndex` function but this should enable the UI for pilots.

https://github.com/mbari-org/dash5/blob/0b527bff294ea6e20a4070bf4612198680a57503/apps/lrauv-dash2/components/ScheduleSection.tsx#L130

```tsx
if (index === 0 && activeDeployment) { // <-- Consider removing activeDeployment as a condition.
      return (
        <div className="flex border-b border-stone-200 py-2 px-4 text-sm">
          <p className="flex-grow text-xs">
            {capitalize(vehicleName)} is scheduled until
            <br /> TBD
          </p>
          <AccessoryButton
            label="Mission"
            icon={faPlus}
            className="mx-2"
            onClick={() => {
              setGlobalModalId({ id: 'newMission' })
            }}
            tight
          />
          <AccessoryButton
            label="Command"
            icon={faPlus}
            tight
            onClick={() => {
              setGlobalModalId({ id: 'newCommand' })
            }}
          />
        </div>
      )
    }
    
 ```

**Comment by ksalamy** [comment]
Removed activeDeployment condition in the if (index === 0) {.....  and changed the "is scheduled until" to "is NOT yet scheduled".  This may need to be reopened to "fine-tune" the label conditions later on.
