### ISSUE TITLE
GMRT Layer Potentially Needs `useMemo`

### ISSUE THREAD

**Issue by jimjeffers** [mbari-org/dash5#243]
**Describe the bug**

**To Reproduce**
1. Go to a [deployment](http://localhost:3000/vehicle/pontus/3000448)
2. Ensure the GMRT base layer is selected
3. Hover over the deployment path or timeline to scrub.
4. Notice the base layer flash or reload each time the scrub interaction updates the target timestamp.

**Expected behavior**
The base layer should not flash or reload upon user interaction with the scrub feature.

**Screenshots**
![CleanShot 2023-03-27 at 13 32 00](https://user-images.githubusercontent.com/9150/228059943-1afa5258-bed8-40d5-83d1-18593ecb52ae.gif)

**Additional context**
Some detail in the WMSTileLayer component is creating this issue. I recommend returning the GMRT layer as a memoized value:

```tsx
const gmrtLayer = useMemo(
    () => (
      <LayersControl.BaseLayer name="GMRT" checked={baseLayer === 'GMRT'}>
        <WMSTileLayer
          params={{
            layers: 'GMRT',
            format: 'image/png',
          }}
          url="https://www.gmrt.org/services/mapserver/wms_merc?"
          eventHandlers={{
            add: addBaseLayerHandler('GMRT'),
          }}
        />{' '}
      </LayersControl.BaseLayer>
    ),
    [baseLayer]
  )
  
  // ...
  
  return (
       // ...
        <LayersControl position="topright">
        {gmrtLayer}
        <LayersControl.BaseLayer
          name="OpenStreetmaps"
          checked={baseLayer === 'OpenStreetmaps'}
        >
          <TileLayer
            attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
            url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
            eventHandlers={{
              add: addBaseLayerHandler('OpenStreetmaps'),
            }}
          />
        </LayersControl.BaseLayer>
        // ...
  )
```

**Comment by ksalamy** [comment]
I believe this issue has been fixed.
