### ISSUE TITLE
Search Broken on Command Modal

### ISSUE THREAD

**Issue by jimjeffers** [mbari-org/dash5#247]
**Describe the bug**
The search field is not updating when attempting to search for a command.

**To Reproduce**
1. Go to 'any vehicle deployment.
2. Click on 'New Command'
3. Attempt to search for a command via the search field in the top right hand side of the modal
4. Notice your text input is not reflected in the search field.

**Expected behavior**
The search field should update. See how the search field works in `New Mission`.

**Screenshots**
![CleanShot 2023-03-28 at 15 48 07](https://user-images.githubusercontent.com/9150/228384252-59090c05-47d9-4d0b-8cd5-659dd0df2958.gif)

**Additional context**
Noticed this when I attempted to replicate #246 . Feel free to assign to me if need be. I would look in the `CommandModal.tsx` file to see how state is being applied to the search field.

**Comment by ksalamy** [comment]
Fixed error using a ref to ensure the last tracked filter is updated so reset code will not continue to fire with searchTerm updates.

**Comment by jimjeffers** [comment]
Looks great @ksalamy !
