### ISSUE TITLE
Change relative size of map/widget and sidebar

### ISSUE THREAD

**Issue by sqshemet** [mbari-org/dash5#286]
**Describe the solution you'd like**
Being able to fullscreen the sidebar pages is nice (and necessary), but I'd love to be able to do something like drag the join between the map and sidebar to change their relative sizes. Seeing the map and log or data side-by-side is incredibly helpful, but with the map dominating the screen it's hard to see enough sidebar data to be useful.

**Comment by ksalamy** [comment]
Added split-view pane (Allotment) to allow resizing of map and sidebar as requested.
